version: '3.1'

services:

  mongo_db:
    image: mongo
    restart: always
    #environment:
      #MONGO_INITDB_ROOT_USERNAME: root
      #MONGO_INITDB_ROOT_PASSWORD: example

  api:
    image: developercan/reading-is-good
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mongo_db
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.data.mongodb.host":"mongo_db",
        "spring.data.mongodb.port":"27017"
      }'
